services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
  logic_gateway:
    build:
      context: "APIGateway"
      dockerfile: "Dockerfile.LogicGateway"
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq