version: '3.3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  logic_gateway:
    build:
      context: "APIGateway"
      dockerfile: "Dockerfile"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq